# Generated by Django 4.1.2 on 2022-10-25 12:54

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_mcq_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=600, unique=True)),
                ('option_a', models.TextField(max_length=600)),
                ('option_b', models.TextField(max_length=600)),
                ('option_c', models.TextField(max_length=600)),
                ('option_d', models.TextField(max_length=600)),
                ('answer', models.TextField(max_length=600, null=True, validators=[course.models.answer_key_validator])),
            ],
        ),
        migrations.CreateModel(
            name='SelectedAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.TextField(max_length=600)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestAppeared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='test',
            old_name='course',
            new_name='fk_course',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='duration',
            new_name='test_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.AddField(
            model_name='course',
            name='creater_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.DeleteModel(
            name='Mcq',
        ),
        migrations.AddField(
            model_name='testappeared',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.test'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectedanswers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='fk_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.test'),
        ),
    ]
